services:
  - type: web
    name: underfish-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: Lichess_token
        sync: false   # you set this in Render Dashboard manually
