services:
  - type: web
    name: underfish-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x stockfish-ubuntu-x86-64-avx2
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4


    startCommand: python main.py

    envVars:
      - key: PORT
        value: 10000
