services:
  - type: web
    name: lichess-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      curl -L -o stockfish.tar.xz https://github.com/official-stockfish/Stockfish/releases/download/sf_16.1/stockfish-ubuntu-x86-64-avx2.tar
      tar -xf stockfish.tar.xz
      mv stockfish-ubuntu-x86-64-avx2/stockfish stockfish
      chmod +x stockfish
    startCommand: python main.py
