services:
  - type: web
    name: underfish-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x stockfish   # <--- force executable permission
    startCommand: python main.py
