services:
  - type: web
    name: underfish-v2
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      curl -L -o stockfish.tar.gz https://stockfishchess.org/files/stockfish-ubuntu-x86-64-avx2.tar
      tar -xvf stockfish.tar.gz
      mv stockfish-ubuntu-x86-64-avx2/stockfish ./stockfish
      chmod +x ./stockfish
    startCommand: python main.py
