services:
  - type: web
    name: lichess-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      curl -L -o stockfish.tar.xz https://github.com/official-stockfish/Stockfish/releases/download/sf_16.1/stockfish-ubuntu-x86-64-avx2.tar
      tar -xf stockfish.tar.xz
      # Find the stockfish binary regardless of folder name
      find . -type f -name "stockfish" -exec mv {} ./stockfish \;
      chmod +x ./stockfish
    startCommand: python main.py
