services:
  - type: worker
    name: underfish-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x ./stockfish/stockfish
    startCommand: python main.py
